import type { NextPage } from 'next'
import Head from 'next/head'
import Score from "../component/score";
import Chart from "../component/chart";
import Discribe from '../component/discribe';
import Report from '../component/report';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="container mt-5">
        <div className="row justify-content-center">
          <div className="col-5">
            <Score/>
          </div>
          <div className="col-5">
            <Chart/>
          </div>
        </div>
          <div className="row justify-content-center mt-2">
            <div className="col-5">
              <Discribe/>
            </div>
            <div className="col-5">
              <Report/>
            </div>
        </div>
      </div>
      </main>
    </div>
  )
}

export default Home
